### ISSUE TITLE
カバレッジの計測をしたい

### ISSUE THREAD

**Issue by ykzts** [baberutv/baberutv#102]
テストの実行には[Jest](https://facebook.github.io/)を使っている。Jestでは

```shell
$ jest --coverage
```

のように`--coverage`というオプション引数をコマンドに追加することでカバレッジの表示を行える。

どの程度テストが書けているのかを継続的に監視できるようになんらかの手段を講じたい。

**Comment by geta6** [comment]
こうしておくとテスト実行してないファイルもカバレッジ対象に含めて0%で計上してくれる

``` json
  "jest": {
    "collectCoverageFrom": [
      "app/**/*.{js,jsx}"
    ]
  },
```

**Comment by ykzts** [comment]
すごい。便利。
