### ISSUE TITLE
対応するウェブブラウザーの一覧を`package.json`に記載する

### ISSUE THREAD

**Issue by ykzts** [baberutv/baberutv#239]
BaberuTVではBabelのプリセットに[`babel-preset-env`](https://www.npmjs.com/package/babel-preset-env)を使っている。`babel-preset-env`は対象とするバージョンを記載したウェブブラウザーのリストをオプションに与えることによって、それらの環境に対応させるためのBabelプラグインを任意に選択し、有効にしてくれるものである。

対象とするウェブブラウザーのリストはBabelの設定に`babel-preset-env`の呼び出しとともに行っている ([`webpack.config.babel.js`の33行目](https://github.com/baberutv/baberutv/blob/v1.3.0/webpack.config.babel.js#L33))。これは`babel-preset-env`のREADMEに書かれている使いかたに従った形である。

`babel-preset-env`はウェブブラウザーの一覧を確認する際に[`browserslist`](https://www.npmjs.com/package/browserslist)を使っている。`browserslist`では`package.json`に`browserslist`というプロパティーを追加して対象とするウェブブラウザーの一覧を書くことができる。

`babel-preset-env`でも`package.json`に記載した値が使えるかどうかは不明ではあるが、もし使えるのであればそちらのほうが`browserslist`に依存するなにか別のものからも認識することができるので便利なのではないだろうか。

検証と確認から進めて行きたい。

**Comment by ykzts** [comment]
`babel-preset-env`はオプションにウェブブラウザーの一覧を与えないと`browserslist`を呼ばず ([`babel-preset-env/src/index.js`の115行目](https://github.com/babel/babel-preset-env/blob/v1.1.11/src/index.js#L115))、また`browserslist`はウェブブラウザーの一覧が引数で与えられていると`package.json`の値を評価しない ([`browserslist/index.js`の行目](https://github.com/ai/browserslist/blob/1.5.1/index.js#L127)) ようだ。これはPull Requestをしたら解決できるような気がしないでもないが、具体的なやりかたについては思いつかず、いかんともしがたい。

とりあえず今できる対応としては`package.json`を`webpack.config.babel.js`から`import`して、値を抜き出すような形にすれば良いのではないかと思う。

**Comment by ykzts** [comment]
`babel-preset-env`に対するPull Requestは既にあった ([babel/babel-preset-env#161](https://github.com/babel/babel-preset-env/pull/161))。

**Comment by yavorsky** [comment]
😊

**Comment by ykzts** [comment]
@yavorsky Thank you very much for the wonderful Pull Request to the babel-preset-env! I am looking forward to being merged.

**Comment by yavorsky** [comment]
@ykzts Yeah, I think we could merge it after next babel's minor release with (https://github.com/babel/babel/pull/4834).
